### ISSUE TITLE
Pick a platform to manage test cases and generate public reports

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/shaping#48]
Now we have test cases tracked in https://docs.google.com/spreadsheets/d/1J2ENPt3lkikBncv-NN_cSaquhsX_0xDSR1GiVhBBNho, which is not easy to manage and doesn't cover report generation. So we should pick one platform to deliver better case tracking.

The basic features requested are simple:

1. easy to manage test cases, including detailed descriptions for cases, like inserting pics, videos, references, etc.
2. support generating public reports, preferably on each commit
3. integrate with GitHub, like sync issues automatically

---

The following are mentioned in Discord that we've used before:

1. JIRA: https://www.atlassian.com/software/jira
4. TestRails: https://www.testrail.com/

The following are mentioned in linear app:

1. Testmo: https://www.testmo.com/
2. Testlodge: https://www.testlodge.com/
3. Bird eats bug: https://birdeatsbug.com/

**Comment by Keith-CY** [comment]
### Testmo

1. integrate with GitHub issue/action: https://www.testmo.com/tools/cypress-test-management
2. integrate with Cypress(which may be used in Neuron's e2e): https://www.testmo.com/tools/cypress-test-management
3. public reports: I didn't find how to share an online report publicly, but it offers an API to export a PDF, which can be attached in github commit: https://www.testmo.com/blog/print-pdf-reports

---

Another similar platform named Testomat(https://testomat.io/) supports public reports
Ref: https://testomat.io/features/test-report-analytics/

**Comment by Keith-CY** [comment]
Any suggestion from @FrederLu @silySuper @littleLip520

**Comment by silySuper** [comment]
Yesterday I tried out some of the platforms mentioned earlier，all of these can both integrate with gitHub and Cypress except Testlodge.
1.As a test case management platform，most tools can meet the requirements.In my personal opinion，Testlodge and TestRail  are easier to use in test case management requirements than others.The functional UI is familiar to the testers. 
2.As a public test report platform,we can solve it by exporting testcases  locally and upload to open website,but  this way can only have test cases results detail ,do not have testers'analysis and summary.Maybe  these platform has customized report generation I have not found yet.（Testlodge I have not found where can export testcases）
3.In my personal opinion， we can record test cases on  TestRail or Test lodge . And  make  our normal test report template according to  project characteristics locally.After we get the test cases result ，we can write test reports follow the report template  and the test case details document is included,then upload it to open website.
Welcome to continue the discussion  ～
@Keith-CY @FrederLu @littleLip520

**Comment by FrederLu** [comment]
> ### Testmo
> 1. integrate with GitHub issue/action: https://www.testmo.com/tools/cypress-test-management
> 2. integrate with Cypress(which may be used in Neuron's e2e): https://www.testmo.com/tools/cypress-test-management
> 3. public reports: I didn't find how to share an online report publicly, but it offers an API to export a PDF, which can be attached in github commit: https://www.testmo.com/blog/print-pdf-reports
> 
> Another similar platform named Testomat(https://testomat.io/) supports public reports Ref: https://testomat.io/features/test-report-analytics/

After reading the documents of testmo, testrail and jira, I found that all test cases support text + pictures, but I didn’t find that it supports video, but I saw a bright spot in testomat https://testomat.io/features/video-capturing-artifacts-tests/, and E2E https://testomat.io/features/import-automated-tests/.
Also testomat has highlights in the public test report https://testomat.io/features/public-test-reports-real-time/.

On the whole, it seems that testomat is more suitable for us than testmo, but unfortunately it feels that testomat is not open source.

See https://www.testmo.com/blog/print-pdf-reports#t8 that testmo publicly shares online report information, but there is no specific operation details.

**Comment by littleLip520** [comment]
I think both testrail and testmo should work.
They are all tools used to manage test cases, have similar test case creation, distribution, and execution processes, and provide similar test report details.
API side:
If we have similar requirements, it is supported in the documents of testrail and testmo.
testrail: https://support.testrail.com/hc/en-us/articles/7077083596436-Introduction-to-the-TestRail-API
testmo: https://docs.testmo.com/api/introduction/using-the-rest-api

Jira is not recommended for the following reasons:
In past work experience, jira is generally used for project & bug life cycle management.
1. It feels too heavy for the presentation that we only want to use it for automated reporting.
2. Jira is not specially used to manage test cases, so it is not the most professional in terms of test case, test plan test execution, etc.

For testomat, the overall function and operation are similar to testrail and testmo, but it lacks the ability to call API

For birdeatsbug, it seems that the usage & operation habits are different from testrail, testmo, and testlodge, and there will be a certain learning cost.

**Comment by Keith-CY** [comment]
> 2.As a public test report platform,we can solve it by exporting testcases locally and upload to open website,but this way can only have test cases results detail ,do not have testers'analysis and summary.Maybe these platform has customized report generation I have not found yet.（Testlodge I have not found where can export testcases）

After checking https://testomat.io/features/real-time-reporting/ I found it supports `public read-only test report`

Also testmo supports exporting PDF(https://www.testmo.com/blog/print-pdf-reports), so the report can be submitted by each GitHub commit. This workflow can be automated by CI, but still a bit burdensome.

**Comment by Keith-CY** [comment]
> See [testmo.com/blog/print-pdf-reports#t8](https://www.testmo.com/blog/print-pdf-reports#t8) that testmo publicly shares online report information, but there is no specific operation details.

I've used testmo so I learned this from its document.
![image](https://github.com/Magickbase/shaping/assets/7271329/7c21cae5-5218-4c8f-a8ed-5035b3f1c450)
It has a button to download/print the pdf, so the pdf can be fetched via an HTTP call. This means, the HTTP call can be executed in CI and upload the returned PDF in github PR/commit.

It's feasible, but not user-friendly.

After all, `public read-only test report` appeals to me very much.

**Comment by Keith-CY** [comment]
> Jira is not recommended for the following reasons: In past work experience, jira is generally used for project & bug life cycle management.
> 
> 1. It feels too heavy for the presentation that we only want to use it for automated reporting.
> 2. Jira is not specially used to manage test cases, so it is not the most professional in terms of test case, test plan test execution, etc.

I think so, Jira is all-in-one but not professional in a specific domain, and it provides many functionalities we've better choices.

**Comment by Keith-CY** [comment]
> API side:
If we have similar requirements, it is supported in the documents of testrail and testmo.
testrail: [support.testrail.com/hc/en-us/articles/7077083596436-Introduction-to-the-TestRail-API](https://support.testrail.com/hc/en-us/articles/7077083596436-Introduction-to-the-TestRail-API)
testmo: [docs.testmo.com/api/introduction/using-the-rest-api](https://docs.testmo.com/api/introduction/using-the-rest-api)

In what case will we use API of testrail or testmo

**Comment by littleLip520** [comment]
> 
Sometimes, we need to write automation code in our own editor (this brying efficiency and flexibility). For example, use cypress to write UI automation scripts. Then use the API to call testrail or testmo to execute the test cases and generate a test report.

**Comment by Keith-CY** [comment]
> > 
> 
> Sometimes, we need to write automation code in our own editor (this brying efficiency and flexibility). For example, use cypress to write UI automation scripts. Then use the API to call testrail or testmo to execute the test cases and generate a test report.

Gotcha

**Comment by FrederLu** [comment]
@Keith-CY @silySuper @littleLip520 
After the research on the test platform some time ago, the test team has discussed and reached a consensus to choose the `TestRail` platform to manage the test cases.
Since the test report preview on testrail will be authenticated, if you need to provide the test report to the outside world, you can send it by email. Files in HTML/PDF format can be attached to the email, and PDF files are convenient for external use.
Attached: Template PDF file [testrail-report-8.pdf](https://github.com/Magickbase/shaping/files/11526909/testrail-report-8.pdf)
